#pragma config(Sensor, port3,  colorHueSensor, sensorVexIQ_Color12Color)
#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  distanceSensor, sensorVexIQ_Distance)
#pragma config(Sensor, port8,  bumpSwitch,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//

/* VEX IQ Ports eksdee
=================================================
Motor Ports:
VEX IQ Port 1:  leftMotor
VEX IQ Port 6:  rightMotor
VEX IQ Port 10: armMotor
VEX IQ Port 11: clawMotor

Sensor Ports:
VEX IQ PORT 3: colorHueSensor
VEX IQ PORT 4: gyroSensor
VEX PORT IQ 7: distanceSensor
VEX IQ Port 8: bumpSwitch
(Bumper Switch)
=================================================
*/

//global vars
string face = "          owo";
int MAX_SPEED = 126;
bool isRunningAutoMode = false;


void forceStopMotors() {
	if (getMotorOverTemp(motor1)== 1 || getMotorOverTemp(motor6)== 1 || getMotorOverTemp(motor10)== 1 || getMotorOverTemp(motor11) == 1) {
		eraseDisplay();
		displayString(1, "%s", "Motor overheating");
		displayString(2, "%s", "detected, forced");
		displayString(3, "%s", "shutdown");
		playSound(soundWrongWay);
		wait10Msec(3000);
		stopAllTasks();
	}
}

	void pet() {
		while (getTouchLEDValue(1)) {
			face = "";
			displayString(3, "%s", "          uwu");
			setTouchLEDRGB(1,230,230,250);
		}
		face = "          owo";
	}

	void lockClaw() {
		motor[motor11] = 100;
		sleep(5);
		motor[motor11] = 0;
	}

	void unlockClaw() {
		motor[motor11] = -100;
		sleep(5);
		motor[motor11] = 0;
	}

	void setWheelsToZero() {
		motor[motor1] = 0;
		motor[motor6] = 0;
	}

	void operateClaw() {
		forceStopMotors();
		motor[motor10] = MAX_SPEED;
	}

	void lowerClaw() {
		motor[motor10] = -MAX_SPEED;
	}

	void reversePosition(int speed, int timeLimit) {
		clearTimer(T1);
		while (time1[T1] < timeLimit) {
			motor[motor1] = speed;
			motor[motor6] = -speed;
			delay(1000);
			setWheelsToZero();
		}
	}

	task main() {

		playSound(soundCarAlarm2);

		repeat(forever) {


			resetMotorEncoder(armMotor);
      pet();
      setTouchLEDColor(1, colorViolet); //set LED to Purple
			tankControl(); //get access to joystick control
			displayString(3, "%s", face);
			armControl(armMotor, BtnRUp, BtnRDown, 90); //get access to arm control


			forceStopMotors(); //temp


			while (getJoystickValue(BtnEUp)) {
				setTouchLEDRGB(1, getColorRedChannel(colorHueSensor), getColorGreenChannel(colorHueSensor), getColorBlueChannel(colorHueSensor));
			}

			while (getJoystickValue(BtnFUp) == 1) {
				lockClaw();
			}

			while (getJoystickValue(BtnFDown) == 1) {
				unlockClaw();
			}

			while (getJoystickValue(BtnRDown) == 1 && getJoystickValue(BtnRUp) == 1) {

				resetMotorEncoder(motor10);

				if (SensorValue[bumpSwitch] == 0) {
					do {
						lowerClaw();
					} while (SensorValue[bumpSwitch] == 0);
				}

				else {
					while (getMotorEncoder(motor10) < 1050) {
						operateClaw();
					}
				}
			}


			if (getJoystickValue(BtnLDown) == 1) {
				reversePosition(MAX_SPEED , 1000);
			}
		}
	}
