#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, encoder)
//This code is automatically generated by the IDE!
/*------------------------------------------------------------------------------------------------
  This program will move your robot forward for 2 seconds. At the end of the program, all motors
  will shut down automatically and turn off.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [Port]              [Name]                    [Location]
    Port 1        			leftMotor          	      Left side motor
    Port 6       				rightMotor         	      Right side motor (reversed)
------------------------------------------------------------------------------------------------*/

task main()
{
	/*
	NEGATIVE VALUE = reverse (anticlockwise)
	POSITIVE VALUE = forward (clockwise)
	
	MAX SPEED = 127
	*/
	
	
	/*
	TASK 1 = Make the bot move forward then wait for 4 seconds. Then make the robot move backwards
	
	TASK 2 = Can you find a way for the robot to move clockwise (rotate)?
	
	*/
	
	
	motor[motor1] = 50; //Set the leftMotor (motor1) to half power (50)
	motor[motor6] = -50; //Set the rightMotor (motor6) to half power (50)
	sleep(2000); //Wait for 2 seconds before continuing on in the program.
}
