#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, encoder)
//This code is automatically generated by the IDE!
/*------------------------------------------------------------------------------------------------
  This program will move your robot forward for 2 seconds. At the end of the program, all motors
  will shut down automatically and turn off.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [Port]              [Name]                    [Location]
    Port 1        			leftMotor          	      Left side motor
    Port 6       				rightMotor         	      Right side motor (reversed)
------------------------------------------------------------------------------------------------*/

task main() //The program starts here, everything inside will be executed
{
	/*
	NEGATIVE VALUE = reverse (anticlockwise)
	POSITIVE VALUE = forward (clockwise)
	
	MAX SPEED = 127
	*/
	
	/*
	|||||||||DO EACH TASK FIRST BEFORE GOING TO THE NEXT|||||||||
	TASK 1 = Make the bot move forward then wait for 4 seconds. Then make the robot move backwards
	
	TASK 2 = Can you find a way for the robot to move clockwise (rotate)?
	
	TASK 3 = Time to make your bot beautiful (because all robots are). Set the TouchLED colour to whatever colour you like! 
	HINT: Use the function setTouchLEDColor(nDevicePort, nColor); but replace the values inside the brackets
	*/
	
	
	motor[motor1] = 50; //Set the leftMotor (motor1) to half power (50)
	sleep(2000); //Wait for 2 seconds before continuing on in the program.
}
